package edu.olya.tour.dao.creators;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * The  {@code RowCreator<T>} interface provides opportunity
 * to build the instance of specified {@code <T>} type
 * with values retrieved from {@code ResultSet}.
 * @param <T> runtime type of the object to be built
 */

public interface RowCreator<T> {
    /**
     *
     * @param rs a database result set of values generated by executing of SQL query
     * @return the object of specified type
     * @throws SQLException if the columnLabel is not valid;
     * if a database access error occurs or this method is
     * called on a closed result set
     */
    public T buildRow(ResultSet rs) throws SQLException;
}
